[[section-introduction-and-goals]]
== Introducción y objetivos

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Descripción general de los requisitos
* Permitir añadir lugares en categorías diferentes.
* Se mostrarán lugares en una ventana tipo mapa.
* A los lugares añadidos se les puede asociar información extra.
* Se podrán gestionar los accesos a la información que comparten con otros usuarios.
* La información sobre los lugares se almacenará en el pod de cada usuario.
* Los usuarios podrán ver lugares e información aportada por sus amigos.
* Se podrán incorporar filtros a los mapas.
* https://arquisoft.github.io/course2223/labEnunciadoPractica.html#requirements
[role="arc42help"]
****
.Contents
Shortsdasdas description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Objetivos de calidad

[options="header",cols="1,2,2"]
|===
|Objetivo de calidad|Descripción|Prioridad
| Interoperabilidad | Los datos deben ser operables entre distintas aplicaciones similares| MEDIUM HIGH
| Disponibilidad | El sistema debe ser capaz de reaccionar a caídas del sistema | HIGH HIGH
| Seguridad | El sistema debe estar actualizado periódicamente| HIGH MEDIUM
|===
[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders
[options="header",cols="1,2,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| HappySw | https://www.linkedin.com/redir/redirect?url=http%3A%2F%2Fwww%2Ehappysoftware%2Ecom&urlhash=p128&trk=about_website| Desarrollo fluido con el objetivo de cumplir los objetivos de calidad
| Ayuntamiento de la ciudad de Bruselas| https://www.brussels.be/city-hall | Aplicación para que los ciudadanos puedan disponer de mapas personalizados sobre lugares y negocios locales de la ciudad.
| Usuarios| | Poder crear mapas personalizados sobre los lugares en los que esté interesado. 
| Negocios| | Permitir crear sus propios espacios como una versión digital de su lugar físico.
|===
[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****
