[[section-introduction-and-goals]]
== Introducción y objetivos

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Descripción general de los requisitos
* Permitir añadir lugares en categorías diferentes.
* Se podrán mostrar lugares en una ventana tipo mapa.
* A los lugares añadidos se les puede asociar información extra.
* Se podrán gestionar los accesos a la información compartida por otros usuarios.
* La información sobre los lugares se almacenará en el pod de cada usuario.
* Los usuarios podrán ver lugares e información aportada por sus amigos.
* Se podrán incorporar filtros a los mapas.

Información más detallada: https://arquisoft.github.io/course2223/labEnunciadoPractica.html#requirements

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Objetivos de calidad

[options="header",cols="1,2,2"]
|===
|Objetivo de calidad|Descripción|Prioridad (IMPORTANCIA, DIFICULTAD)
| Interoperabilidad | Los datos deben ser operables entre distintas aplicaciones similares - Compatibilidad | HIGH, MEDIUM
| Disponibilidad | El sistema debe ser capaz de reaccionar a caídas del sistema y ofrecer el servicio adecuadamente el máximo tiempo posible | MEDIUM, HIGH
| Seguridad | El sistema debe ser revisado y actualizado periódicamente, y aplicar las medidas de seguridad pertinentes de forma correcta - Privacidad | HIGH, MEDIUM
| Escalabilidad | El sistema debe reaccionar y no decrementar su rendimiento ante un crecimiento exponencial de usuarios y datos | HIGH, HIGH
|===
[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders
[options="header",cols="1,1,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| HappySw | https://www.happysoftware.com/tc/index.php | Cumplimiento de los objetivos de calidad y obtención de un sistema óptimo
| Ayuntamiento Bruselas| https://www.brussels.be/city-hall | Entrega de una aplicación para que los ciudadanos puedan disponer de mapas personalizados sobre lugares y negocios
| Equipo de desarrollo | https://github.com/Arquisoft/lomap_es3c | Desarrollo y entrega en plazo del producto solicitado, cumpliendo con todos los requisitos
| Usuarios| | Posibilidad de crear mapas personalizados sobre los lugares en los que estén interesados, e interaccionar con ellos
| Negocios| | Permitir crear sus propios espacios como una versión digital de su lugar físico
|===
[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****
