[[section-runtime-view]]
== Vista en tiempo de ejecución


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****
=== Nivel 0
==== Identificación
[plantuml,"Sequence diagram02",png]
----
actor Usuario
entity LoMap
entity Inrupt
Usuario -> LoMap: Solicita identificación
LoMap--> Inrupt: Redirige identificación
Inrupt--> LoMap: Envía ventana de identificación
LoMap--> Usuario: Envía ventana de inicio de sesión
Usuario -> LoMap: Introduce información de identificación
LoMap--> Inrupt: Envía información de identificación
Inrupt--> Inrupt: Comprueba información
alt Información de identificación correcta
Inrupt-->Lomap: Identificación correcta
LoMap--> Usuario: Muestra resultado de identificación
else Información de identificación incorrecta
Inrupt-->Lomap: Identificación incorrecta
LoMap--> Usuario: Muestra resultado de identificación
end
----

==== Añadir lugar en mapa
[plantuml,"Sequence diagram03",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar en el mapa
Lomap --> Usuario: 
Usuario -> LoMap: Añade lugar en el mapa
database Pod as "Pods"
LoMap--> Usuario: Envía ventana de creación de un lugar
Usuario-> LoMap: Añade información al lugar
LoMap-> Pod: Añade lugar
Pod--> LoMap: Confirma operación
LoMap--> Usuario: Muestra nuevo lugar en el mapa
----
==== Compartir lugar
[plantuml,"Sequence diagram04",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar (ya añadido)
Usuario -> LoMap: Compartir lugar con amigos
database Pod as "Pods"
LoMap-> Pod : Añade lugar
Pod--> LoMap: Confirma operación
LoMap--> Usuario: Muestra nuevo lugar en los lugares compartidos
----
==== Añadir información a lugar
[plantuml,"Sequence diagram05",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar (ya añadido)
Usuario -> LoMap: Añadir información al lugar
database Pod as "Pods"
LoMap-> Pod: Actualiza información sobre el lugar
Pod--> LoMap: Confirma operación
LoMap--> Usuario: Muestra lugar con información actualizada
----
==== Visualizar lugares
[plantuml,"Sequence diagram06",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicita ver los lugares
database Pod as "Pods"
LoMap-> Pod: Solicita los lugares del usuario
Pod--> LoMap: Envía lugares
LoMap--> Usuario: Muestra lugares
----
==== Filtrar lugares
[plantuml,"Sequence diagram07",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Filtrar lugares
LoMap--> Usuario: Envía ventana de filtros
Usuario -> LoMap: Introduce filtros
database Pod as "Pods"
LoMap--> LoMap: Comprobar validez de filtros
alt Filtros correctos
LoMap-> Pod: Solicitar los lugares filtrados
Pod--> LoMap: Devolver lugares filtrados
LoMap--> Usuario: Mostrar lugares
else Filtros incorrectos
Pod --> LoMap: Notifica sobre error
LoMap--> Usuario: Reinicia ventana de filtros
end
----
==== Añadir amigo
[plantuml,"Sequence diagram08",png]
----
actor Usuario1
actor Usuario2
Usuario2 -> Usuario1: Envía identificador de amigo
entity LoMap
Usuario1->LoMap: Añadir amigo
database Pod as "Pods"
LoMap-> Pod: Añade un amigo
Pod--> LoMap: Confirma operación
LoMap--> Usuario1: Muestra lista de amigos
----
==== Listar lugares de amigos
[plantuml,"Sequence diagram09",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicitar ver los lugares de amigos
database Pod as "Pods"
LoMap-> Pod: Solicitar los lugares compartidos por amigos
Pod--> LoMap: Enviar lugares
LoMap--> Usuario: Mostrar lugares de amigos
----
=== Nivel 1
==== Identificación
[plantuml,"Sequence diagram2",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicita inicio de sesión
entity API_REST
database MongoDB as "MongoDB"
LoMap--> Usuario: Envía ventana de inicio de sesión
Usuario -> LoMap: Introduce información de inicio de sesión
LoMap--> API_REST: Envía información de inicio de sesión
API_REST -> MongoDB: Busca información
MongoDB -> API_REST: Envía información
API_REST--> API_REST: Comprueba información
alt Información de inicio correcta
API_REST--> LoMap: Notifica sobre inicio correcto
LoMap--> Usuario: Muestra resultado de inicio de sesión
else Información de inicio incorrecta
API_REST--> LoMap: Notifica sobre inicio de sesión incorrecto
LoMap--> Usuario: Notifica sobre inicio de sesión incorrecto
end
----

==== Añadir lugar en mapa
[plantuml,"Sequence diagram3",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar en el mapa
Usuario -> LoMap: Añade lugar en el mapa
entity API_REST
database Pod as "Pods"
LoMap--> Usuario: Envía ventana de creación de un lugar
Usuario-> LoMap: Añade información al lugar
LoMap-> API_REST: Envía información sobre el lugar
API_REST-> Pod: Añade lugar
Pod--> API_REST: Confirma operación
API_REST--> LoMap: Confirma operación
LoMap--> Usuario: Muestra nuevo lugar en el mapa
----
==== Compartir lugar
[plantuml,"Sequence diagram4",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar (ya añadido)
Usuario -> LoMap: Compartir lugar con amigos
entity API_REST
database Pod as "Pods"
LoMap-> API_REST: Envía información sobre el lugar
API_REST-> Pod : Añade lugar
Pod--> API_REST: Confirma operación
API_REST--> LoMap: Confirma operación
LoMap--> Usuario: Muestra nuevo lugar en los lugares compartidos
----
==== Añadir información a lugar
[plantuml,"Sequence diagram5",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar (ya añadido)
Usuario -> LoMap: Añadir información al lugar
entity API_REST
database Pod as "Pods"
LoMap-> API_REST: Envía información adicional sobre el lugar
API_REST-> Pod: Actualiza información sobre el lugar
Pod--> API_REST: Confirma operación
API_REST--> LoMap: Confirma operación
LoMap--> Usuario: Muestra lugar con información actualizada
----
==== Visualizar lugares
[plantuml,"Sequence diagram6",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicita ver los lugares
entity API_REST
database Pod as "Pods"
LoMap-> API_REST: Envía solicitud ver lugares
API_REST-> Pod: Solicita los lugares del usuario
Pod--> API_REST: Envía lugares
API_REST--> LoMap: Envía lugares
LoMap--> Usuario: Muestra lugares
----
==== Filtrar lugares
[plantuml,"Sequence diagram7",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Filtrar lugares
LoMap--> Usuario: Envía ventana de filtros
Usuario -> LoMap: Introduce filtros
entity API_REST
database Pod as "Pods"
LoMap-> API_REST: Enviar solicitud filtrada
API_REST--> API_REST: Comprobar validez de filtros
alt Filtros correctos
API_REST-> Pod: Solicitar los lugares filtrados
Pod--> API_REST: Devolver lugares filtrados
API_REST--> LoMap: Enviar lugares
LoMap--> Usuario: Mostrar lugares
else Filtros incorrectos
API_REST --> LoMap: Notifica sobre filtrado incorrecto
LoMap--> Usuario: Reinicia ventana de filtros
end
----
==== Añadir amigo
[plantuml,"Sequence diagram8",png]
----
actor Usuario1
actor Usuario2
Usuario2 -> Usuario1: Envía identificador de amigo
entity LoMap
Usuario1->LoMap: Añadir amigo
entity API_REST
LoMap-> API_REST: Envía solicitud
database Pod as "Pods"
API_REST-> Pod: Añade un amigo
Pod--> API_REST: Confirma operación
API_REST--> LoMap: Confirma operación
LoMap--> Usuario1: Muestra lista de amigos
----
==== Listar lugares de amigos
[plantuml,"Sequence diagram9",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicitar ver los lugares de amigos
entity API_REST
database Pod as "Pods"
LoMap-> API_REST: Enviar solicitud ver lugares
API_REST-> Pod: Solicitar los lugares compartidos por amigos
Pod--> API_REST: Devolver lugares de amigos
API_REST--> LoMap: Enviar lugares
LoMap--> Usuario: Mostrar lugares de amigos
----