[[section-runtime-view]]
== Vista en tiempo de ejecución


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****
=== Nivel 0
==== Identificación
[plantuml,"Sequence diagram02",png]
----
actor Usuario
entity LoMap
entity Inrupt
Usuario -> LoMap: Solicita identificación
LoMap--> Inrupt: Redirige identificación
Inrupt--> LoMap: Envía ventana de identificación
LoMap--> Usuario: Envía ventana de inicio de sesión
Usuario -> LoMap: Introduce información de identificación
LoMap--> Inrupt: Envía información de identificación
Inrupt--> Inrupt: Comprueba información
alt Información de identificación correcta
Inrupt-->LoMap: Identificación correcta
LoMap--> Usuario: Muestra resultado de identificación
else Información de identificación incorrecta
Inrupt-->LoMap: Identificación incorrecta
LoMap--> Usuario: Muestra resultado de identificación
end
----

==== Añadir lugar en mapa
[plantuml,"Sequence diagram03",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar en el mapa
LoMap --> Usuario: 
Usuario -> LoMap: Añade lugar en el mapa
database Pod as "Pods"
LoMap--> Usuario: Envía ventana de creación de un lugar
Usuario-> LoMap: Añade información al lugar
LoMap-> Pod: Añade lugar
Pod--> LoMap: Confirma operación
LoMap--> Usuario: Muestra nuevo lugar en el mapa
----
==== Compartir lugares
[plantuml,"Sequence diagram04",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Compartir con amigos
LoMap --> Usuario: Envía ventana compartir lugares
database Pod as "Pods"
Usuario -> LoMap: Amigo seleccionado
LoMap-> Pod : Modifica permisos
Pod--> LoMap: Confirma operación
LoMap--> Usuario: Confirma operación
----
==== Añadir review a lugar
[plantuml,"Sequence diagram05",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar (ya añadido)
LoMap-->Usuario: Vista punto
Usuario -> LoMap: Añadir review al lugar
database Pod as "Pods"
LoMap-> Pod: Actualiza información sobre el lugar
Pod--> LoMap: Confirma operación
LoMap--> Usuario: Confirma operación
----
==== Visualizar lugares
[plantuml,"Sequence diagram06",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicita ver los mapas
LoMap --> Usuario: Muestra mapas
Usuario -> LoMap: Selecciona un mapa
database Pod as "Pods"
LoMap-> Pod: Solicita los puntos del mapa
Pod--> LoMap: Envía lugares
LoMap--> Usuario: Muestra lugares
----
==== Filtrar lugares
[plantuml,"Sequence diagram07",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Introduce filtros (con un mapa seleccionado previamente)
LoMap--> LoMap: Aplica los filtros
LoMap--> Usuario: Mostrar lugares filtrados
----
==== Enviar solicitud de amigo
[plantuml,"Sequence diagram08",png]
----
actor Usuario1
actor Usuario2
Usuario2 -> Usuario1: Envía identificador de amigo
entity LoMap
Usuario1->LoMap: Envia solicitud amigo
LoMap--> Usuario2: Envía solicitud
----
==== Listar lugares de amigos
[plantuml,"Sequence diagram09",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicitar ver los lugares de amigos
database Pod as "Pods"
LoMap-> Pod: Solicitar los lugares compartidos por amigos
Pod--> LoMap: Enviar lugares
LoMap--> Usuario: Mostrar lugares de amigos
----
=== Nivel 1
==== Identificación
[plantuml,"Sequence diagram2",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicita inicio de sesión
entity API_REST
database Pods as "Pods"
LoMap--> Usuario: Envía ventana de inicio de sesión
Usuario -> LoMap: Introduce información de inicio de sesión
LoMap--> API_REST: Envía información de inicio de sesión
API_REST -> Pods: Busca información
Pods -> API_REST: Envía información
API_REST--> API_REST: Comprueba información
alt Información de inicio correcta
API_REST--> LoMap: Notifica sobre inicio correcto
LoMap--> Usuario: Muestra resultado de inicio de sesión
else Información de inicio incorrecta
API_REST--> LoMap: Notifica sobre inicio de sesión incorrecto
LoMap--> Usuario: Notifica sobre inicio de sesión incorrecto
end
----

==== Añadir lugar en mapa
[plantuml,"Sequence diagram3",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar en el mapa
Usuario -> LoMap: Añade lugar en el mapa
entity API_REST
database Pod as "Pods"
LoMap--> Usuario: Envía ventana de creación de un lugar
Usuario-> LoMap: Añade información al lugar
LoMap-> API_REST: Envía información sobre el lugar
API_REST-> Pod: Añade lugar
Pod--> API_REST: Confirma operación
API_REST--> LoMap: Confirma operación
LoMap--> Usuario: Muestra nuevo lugar en el mapa
----
==== Compartir lugares
[plantuml,"Sequence diagram4",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Compartir con amigos
LoMap --> Usuario: Envía ventana compartir lugares
entity API_REST
database Pod as "Pods"
Usuario -> LoMap: Amigo seleccionado
LoMap->API_REST: Solicita modificar permisos
API_REST-> Pod : Modifica permisos
Pod--> API_REST: Confirma operación
API_REST -->LoMap:Confirma operación
LoMap--> Usuario: Confirma operación
----
==== Añadir review a lugar
[plantuml,"Sequence diagram5",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Selecciona un lugar (ya añadido)
LoMap-->Usuario: Vista punto
Usuario -> LoMap: Añadir review al lugar
entity API_REST
LoMap-> API_REST: Sobrescribir punto con review nueva
database Pod as "Pods"
API_REST-> Pod: Actualiza información sobre el lugar
Pod--> API_REST: Confirma operación
API_REST--> LoMap: Confirma operación
LoMap--> Usuario: Confirma operación
----
==== Visualizar lugares
[plantuml,"Sequence diagram6",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicita ver los lugares
entity API_REST
database Pod as "Pods"
LoMap-> API_REST: Envía solicitud ver lugares
API_REST-> Pod: Solicita los lugares del usuario
Pod--> API_REST: Envía lugares
API_REST--> LoMap: Envía lugares
LoMap--> Usuario: Muestra lugares
----
==== Filtrar lugares
[plantuml,"Sequence diagram7",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Introduce filtros (con un mapa seleccionado previamente)
LoMap--> LoMap: Aplica los filtros
LoMap--> Usuario: Mostrar lugares filtrados
----
==== Enviar solicitud de amigo
[plantuml,"Sequence diagram8",png]
----
actor Usuario1
actor Usuario2
Usuario2 -> Usuario1: Envía identificador de amigo
entity LoMap
database MongoDB as "MongoDB"
Usuario1->LoMap: Envia solicitud amigo
LoMap-->LoMap: Comprueba existencia y amistad usuario2
alt Existe y no son amigos
LoMap->MongoDB: Registrar solicitud
MongoDB-->LoMap: Envía solicitud
LoMap--> Usuario2: Envía solicitud
else No existe o no son amigos
LoMap--> Usuario1: Informa error
end
----
==== Listar lugares de amigos
[plantuml,"Sequence diagram9",png]
----
actor Usuario
entity LoMap
Usuario -> LoMap: Solicitar ver los lugares de amigos
entity API_REST
database Pod as "Pods"
LoMap-> API_REST: Solicitar los lugares compartidos por amigos
API_REST->Pod:Solicitar los lugares compartidos por amigos
Pod--> API_REST: Enviar lugares
API_REST--> LoMap: Enviar lugares
LoMap--> Usuario: Mostrar lugares de amigos
----